version: "3.8"

services:
  db:
    image: postgres:18
    container_name: jira-synergy-db
    restart: always
    environment:
      # Использование переменных окружения из .env файла
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Проброс портов для БД
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data

volumes:
  postgres_data:
